//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class vi_VN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal vi_VN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ABM_Web.App_GlobalResources.vi-VN", typeof(vi_VN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hanot Pest Control Company.
        /// </summary>
        public static string Breadcrumb_ABM {
            get {
                return ResourceManager.GetString("Breadcrumb_ABM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng điều khiển.
        /// </summary>
        public static string Breadcrumb_Dashboard {
            get {
                return ResourceManager.GetString("Breadcrumb_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin thành viên.
        /// </summary>
        public static string Breadcrumb_Personalization {
            get {
                return ResourceManager.GetString("Breadcrumb_Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác.
        /// </summary>
        public static string Btn_Action {
            get {
                return ResourceManager.GetString("Btn_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        public static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string Btn_Close {
            get {
                return ResourceManager.GetString("Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        public static string Btn_Complete {
            get {
                return ResourceManager.GetString("Btn_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới.
        /// </summary>
        public static string Btn_Create {
            get {
                return ResourceManager.GetString("Btn_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải về.
        /// </summary>
        public static string Btn_Download {
            get {
                return ResourceManager.GetString("Btn_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nổi bật.
        /// </summary>
        public static string Btn_Focus {
            get {
                return ResourceManager.GetString("Btn_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di vào bảng và cuộn chuột.
        /// </summary>
        public static string Btn_Left_Right_Tooltip {
            get {
                return ResourceManager.GetString("Btn_Left_Right_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa.
        /// </summary>
        public static string Btn_Locked {
            get {
                return ResourceManager.GetString("Btn_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Btn_Login {
            get {
                return ResourceManager.GetString("Btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string Btn_Otp {
            get {
                return ResourceManager.GetString("Btn_Otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string Btn_Print {
            get {
                return ResourceManager.GetString("Btn_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string Btn_Print_Detail {
            get {
                return ResourceManager.GetString("Btn_Print_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng hợp.
        /// </summary>
        public static string Btn_Print_Synthesis {
            get {
                return ResourceManager.GetString("Btn_Print_Synthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất bản.
        /// </summary>
        public static string Btn_Published {
            get {
                return ResourceManager.GetString("Btn_Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gỡ bài.
        /// </summary>
        public static string Btn_Removed {
            get {
                return ResourceManager.GetString("Btn_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu lại.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thiết lập của bạn.
        /// </summary>
        public static string Btn_Save_Personalization {
            get {
                return ResourceManager.GetString("Btn_Save_Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở khóa.
        /// </summary>
        public static string Btn_UnLocked {
            get {
                return ResourceManager.GetString("Btn_UnLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Báo Cáo.
        /// </summary>
        public static string Btn_View {
            get {
                return ResourceManager.GetString("Btn_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ sử lý.
        /// </summary>
        public static string Btn_Wait {
            get {
                return ResourceManager.GetString("Btn_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015 Hanot Pest Control Company.
        /// </summary>
        public static string Copyright_Content {
            get {
                return ResourceManager.GetString("Copyright_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minhson84@gmail.com.
        /// </summary>
        public static string Copyright_Email {
            get {
                return ResourceManager.GetString("Copyright_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BannerId.
        /// </summary>
        public static string G_C_BannerId {
            get {
                return ResourceManager.GetString("G_C_BannerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookingId.
        /// </summary>
        public static string G_C_BookingId {
            get {
                return ResourceManager.GetString("G_C_BookingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        public static string G_C_Click {
            get {
                return ResourceManager.GetString("G_C_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hợp đồng.
        /// </summary>
        public static string G_C_Contract {
            get {
                return ResourceManager.GetString("G_C_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng.
        /// </summary>
        public static string G_C_Customer {
            get {
                return ResourceManager.GetString("G_C_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban.
        /// </summary>
        public static string G_C_Departments {
            get {
                return ResourceManager.GetString("G_C_Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm làm việc.
        /// </summary>
        public static string G_C_Group {
            get {
                return ResourceManager.GetString("G_C_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTTĐ.
        /// </summary>
        public static string G_C_GTTD_1 {
            get {
                return ResourceManager.GetString("G_C_GTTD_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị thay đổi.
        /// </summary>
        public static string G_C_GTTD_2 {
            get {
                return ResourceManager.GetString("G_C_GTTD_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị thực chạy chênh lệch phát sinh khi hợp đồng thay đổi.
        /// </summary>
        public static string G_C_GTTD_Tooltip {
            get {
                return ResourceManager.GetString("G_C_GTTD_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng.
        /// </summary>
        public static string G_C_HD {
            get {
                return ResourceManager.GetString("G_C_HD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        public static string G_C_IntoMoney {
            get {
                return ResourceManager.GetString("G_C_IntoMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến mại.
        /// </summary>
        public static string G_C_KM {
            get {
                return ResourceManager.GetString("G_C_KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhãn hàng.
        /// </summary>
        public static string G_C_Label {
            get {
                return ResourceManager.GetString("G_C_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lệch treo hạ.
        /// </summary>
        public static string G_C_LTH {
            get {
                return ResourceManager.GetString("G_C_LTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu mới nhất lấy về hoàn thành hàng ngày vào &lt;strong&gt;11h&lt;/strong&gt;.
        /// </summary>
        public static string G_C_LTH_Notification {
            get {
                return ResourceManager.GetString("G_C_LTH_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội bộ.
        /// </summary>
        public static string G_C_NB {
            get {
                return ResourceManager.GetString("G_C_NB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Chưa VAT).
        /// </summary>
        public static string G_C_Not_Vat {
            get {
                return ResourceManager.GetString("G_C_Not_Vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bộ phận.
        /// </summary>
        public static string G_C_Parts {
            get {
                return ResourceManager.GetString("G_C_Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        public static string G_C_Product {
            get {
                return ResourceManager.GetString("G_C_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string G_C_RowNumber {
            get {
                return ResourceManager.GetString("G_C_RowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string G_C_SL {
            get {
                return ResourceManager.GetString("G_C_SL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        public static string G_C_Staff {
            get {
                return ResourceManager.GetString("G_C_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thực chạy.
        /// </summary>
        public static string G_C_TC {
            get {
                return ResourceManager.GetString("G_C_TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thực thu.
        /// </summary>
        public static string G_C_TT {
            get {
                return ResourceManager.GetString("G_C_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string G_C_Unit {
            get {
                return ResourceManager.GetString("G_C_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string G_C_View {
            get {
                return ResourceManager.GetString("G_C_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên website.
        /// </summary>
        public static string G_C_Website {
            get {
                return ResourceManager.GetString("G_C_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn điều kiện tìm kiếm để hiển thị danh sách..
        /// </summary>
        public static string G_Search_Title {
            get {
                return ResourceManager.GetString("G_Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức quảng cáo.
        /// </summary>
        public static string L_AdvertisingType {
            get {
                return ResourceManager.GetString("L_AdvertisingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        public static string L_Banner {
            get {
                return ResourceManager.GetString("L_Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúc bạn ngày mới tốt lành!.
        /// </summary>
        public static string L_BestWishForYou {
            get {
                return ResourceManager.GetString("L_BestWishForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        public static string L_Booking {
            get {
                return ResourceManager.GetString("L_Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục.
        /// </summary>
        public static string L_Category {
            get {
                return ResourceManager.GetString("L_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        public static string L_Company {
            get {
                return ResourceManager.GetString("L_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hợp đồng.
        /// </summary>
        public static string L_Contract {
            get {
                return ResourceManager.GetString("L_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị hợp đồng nội bộ.
        /// </summary>
        public static string L_Contract_NB {
            get {
                return ResourceManager.GetString("L_Contract_NB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string L_Customer {
            get {
                return ResourceManager.GetString("L_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        public static string L_DateRange {
            get {
                return ResourceManager.GetString("L_DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        public static string L_Departments {
            get {
                return ResourceManager.GetString("L_Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        public static string L_Forgot_Password {
            get {
                return ResourceManager.GetString("L_Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm làm việc.
        /// </summary>
        public static string L_Group {
            get {
                return ResourceManager.GetString("L_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào,.
        /// </summary>
        public static string L_Hello {
            get {
                return ResourceManager.GetString("L_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn hàng.
        /// </summary>
        public static string L_Label {
            get {
                return ResourceManager.GetString("L_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đăng nhập.
        /// </summary>
        public static string L_Login_Title {
            get {
                return ResourceManager.GetString("L_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp.
        /// </summary>
        public static string L_OrderBy {
            get {
                return ResourceManager.GetString("L_OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập OTP từ điện thoại của bạn.
        /// </summary>
        public static string L_Otp {
            get {
                return ResourceManager.GetString("L_Otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số trang.
        /// </summary>
        public static string L_PageNumber {
            get {
                return ResourceManager.GetString("L_PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận.
        /// </summary>
        public static string L_Parts {
            get {
                return ResourceManager.GetString("L_Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string L_Password {
            get {
                return ResourceManager.GetString("L_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string L_Product {
            get {
                return ResourceManager.GetString("L_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string L_Search {
            get {
                return ResourceManager.GetString("L_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string L_Staff {
            get {
                return ResourceManager.GetString("L_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string L_Status {
            get {
                return ResourceManager.GetString("L_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ.
        /// </summary>
        public static string L_Support {
            get {
                return ResourceManager.GetString("L_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập từ khóa....
        /// </summary>
        public static string L_TypeToFilter {
            get {
                return ResourceManager.GetString("L_TypeToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string L_Unit {
            get {
                return ResourceManager.GetString("L_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string L_Username {
            get {
                return ResourceManager.GetString("L_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string L_Website {
            get {
                return ResourceManager.GetString("L_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chờ trong giây lát .
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ưu tiên.
        /// </summary>
        public static string M_Adv_Table_Col_Priority {
            get {
                return ResourceManager.GetString("M_Adv_Table_Col_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại.
        /// </summary>
        public static string M_Adv_Table_Col_Type_Name {
            get {
                return ResourceManager.GetString("M_Adv_Table_Col_Type_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn.
        /// </summary>
        public static string M_Adv_Table_Col_Url {
            get {
                return ResourceManager.GetString("M_Adv_Table_Col_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách bài viết.
        /// </summary>
        public static string M_Article_Panel_Title {
            get {
                return ResourceManager.GetString("M_Article_Panel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người xuất bản.
        /// </summary>
        public static string M_Article_Table_Col_ApprovedBy {
            get {
                return ResourceManager.GetString("M_Article_Table_Col_ApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục.
        /// </summary>
        public static string M_Article_Table_Col_Category {
            get {
                return ResourceManager.GetString("M_Article_Table_Col_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày xuất bản.
        /// </summary>
        public static string M_Article_Table_Col_PublishOn {
            get {
                return ResourceManager.GetString("M_Article_Table_Col_PublishOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề bài viết.
        /// </summary>
        public static string M_Article_Table_Col_Title {
            get {
                return ResourceManager.GetString("M_Article_Table_Col_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách chuyên mục.
        /// </summary>
        public static string M_Category_Panel_Title {
            get {
                return ResourceManager.GetString("M_Category_Panel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấp.
        /// </summary>
        public static string M_Category_Table_Col_Level {
            get {
                return ResourceManager.GetString("M_Category_Table_Col_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chuyên mục.
        /// </summary>
        public static string M_Category_Table_Col_Name {
            get {
                return ResourceManager.GetString("M_Category_Table_Col_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ưu tiên.
        /// </summary>
        public static string M_Category_Table_Col_Priority {
            get {
                return ResourceManager.GetString("M_Category_Table_Col_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người phát triển.
        /// </summary>
        public static string M_Developer_L_Name {
            get {
                return ResourceManager.GetString("M_Developer_L_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách lỗi.
        /// </summary>
        public static string M_Error_Panel_Title {
            get {
                return ResourceManager.GetString("M_Error_Panel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        public static string M_Error_Table_Col_CreatedDate {
            get {
                return ResourceManager.GetString("M_Error_Table_Col_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string M_Error_Table_Col_Desc {
            get {
                return ResourceManager.GetString("M_Error_Table_Col_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư điện tử.
        /// </summary>
        public static string M_Error_Table_Col_Email {
            get {
                return ResourceManager.GetString("M_Error_Table_Col_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string M_Error_Table_Col_FullName {
            get {
                return ResourceManager.GetString("M_Error_Table_Col_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh.
        /// </summary>
        public static string M_Error_Table_Col_Image {
            get {
                return ResourceManager.GetString("M_Error_Table_Col_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ưu tiên.
        /// </summary>
        public static string M_Error_Table_Col_Priority {
            get {
                return ResourceManager.GetString("M_Error_Table_Col_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhóm.
        /// </summary>
        public static string M_Group_Panel_Title {
            get {
                return ResourceManager.GetString("M_Group_Panel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string M_Group_Table_Col_Desc {
            get {
                return ResourceManager.GetString("M_Group_Table_Col_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm.
        /// </summary>
        public static string M_Group_Table_Col_Name {
            get {
                return ResourceManager.GetString("M_Group_Table_Col_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ ưu tiên.
        /// </summary>
        public static string M_Group_Table_Col_Row {
            get {
                return ResourceManager.GetString("M_Group_Table_Col_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string M_Menu_L_Desc {
            get {
                return ResourceManager.GetString("M_Menu_L_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà phát triển.
        /// </summary>
        public static string M_Menu_L_Developers {
            get {
                return ResourceManager.GetString("M_Menu_L_Developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin người phát triển chức năng.
        /// </summary>
        public static string M_Menu_L_Developers_Desc {
            get {
                return ResourceManager.GetString("M_Menu_L_Developers_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn.
        /// </summary>
        public static string M_Menu_L_Guide {
            get {
                return ResourceManager.GetString("M_Menu_L_Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết lập bài viết hướng dẫn cho chức năng.
        /// </summary>
        public static string M_Menu_L_Guide_Desc {
            get {
                return ResourceManager.GetString("M_Menu_L_Guide_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng.
        /// </summary>
        public static string M_Menu_L_Menu {
            get {
                return ResourceManager.GetString("M_Menu_L_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình chức năng của hệ thống.
        /// </summary>
        public static string M_Menu_L_Menu_Desc {
            get {
                return ResourceManager.GetString("M_Menu_L_Menu_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chức năng.
        /// </summary>
        public static string M_Menu_L_Name {
            get {
                return ResourceManager.GetString("M_Menu_L_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham số.
        /// </summary>
        public static string M_Menu_L_Params {
            get {
                return ResourceManager.GetString("M_Menu_L_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng cha.
        /// </summary>
        public static string M_Menu_L_Parent {
            get {
                return ResourceManager.GetString("M_Menu_L_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ ưu tiên.
        /// </summary>
        public static string M_Menu_L_Priority {
            get {
                return ResourceManager.GetString("M_Menu_L_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn.
        /// </summary>
        public static string M_Menu_L_Source {
            get {
                return ResourceManager.GetString("M_Menu_L_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string M_Menu_L_Status {
            get {
                return ResourceManager.GetString("M_Menu_L_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách chức năng.
        /// </summary>
        public static string M_Menu_Panel_Title {
            get {
                return ResourceManager.GetString("M_Menu_Panel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biểu tượng.
        /// </summary>
        public static string M_Menu_Table_Col_Icon {
            get {
                return ResourceManager.GetString("M_Menu_Table_Col_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấp.
        /// </summary>
        public static string M_Menu_Table_Col_Level {
            get {
                return ResourceManager.GetString("M_Menu_Table_Col_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chức năng.
        /// </summary>
        public static string M_Menu_Table_Col_Name {
            get {
                return ResourceManager.GetString("M_Menu_Table_Col_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản.
        /// </summary>
        public static string M_Personalization_L_Account_Infomation {
            get {
                return ResourceManager.GetString("M_Personalization_L_Account_Infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cá nhân.
        /// </summary>
        public static string M_Personalization_L_Individuals {
            get {
                return ResourceManager.GetString("M_Personalization_L_Individuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết lập chức năng.
        /// </summary>
        public static string M_Personalization_L_SettingMenu {
            get {
                return ResourceManager.GetString("M_Personalization_L_SettingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo Kênh.
        /// </summary>
        public static string M_Personalization_L_SettingMenu_BaoCaoKenh {
            get {
                return ResourceManager.GetString("M_Personalization_L_SettingMenu_BaoCaoKenh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin thực chạy cho các báo của đối tác.
        /// </summary>
        public static string M_Personalization_L_SettingMenu_BaoCaoKenh_Desc {
            get {
                return ResourceManager.GetString("M_Personalization_L_SettingMenu_BaoCaoKenh_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        public static string M_Personalization_L_SettingMenu_Booking {
            get {
                return ResourceManager.GetString("M_Personalization_L_SettingMenu_Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đăng ký, đặt vị trí quảng cáo và theo dõi tiến trình thực hiện..
        /// </summary>
        public static string M_Personalization_L_SettingMenu_Booking_Desc {
            get {
                return ResourceManager.GetString("M_Personalization_L_SettingMenu_Booking_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng công nợ.
        /// </summary>
        public static string M_Personalization_L_SettingMenu_HDCN {
            get {
                return ResourceManager.GetString("M_Personalization_L_SettingMenu_HDCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý hợp đồng, công nợ, thông tin khách hàng &amp; nhân sự..
        /// </summary>
        public static string M_Personalization_L_SettingMenu_HDCN_Desc {
            get {
                return ResourceManager.GetString("M_Personalization_L_SettingMenu_HDCN_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thực chạy.
        /// </summary>
        public static string M_Personalization_L_SettingMenu_ThucChay {
            get {
                return ResourceManager.GetString("M_Personalization_L_SettingMenu_ThucChay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống báo cáo thực chạy theo nhiều chiều khác nhau..
        /// </summary>
        public static string M_Personalization_L_SettingMenu_ThucChay_Desc {
            get {
                return ResourceManager.GetString("M_Personalization_L_SettingMenu_ThucChay_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý công việc.
        /// </summary>
        public static string M_Personalization_L_Tasks {
            get {
                return ResourceManager.GetString("M_Personalization_L_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cá nhân hóa.
        /// </summary>
        public static string M_Personalization_Page_Title {
            get {
                return ResourceManager.GetString("M_Personalization_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản, đổi mật khẩu và thiết lập chức năng..
        /// </summary>
        public static string M_Personalization_Page_Title_Desc {
            get {
                return ResourceManager.GetString("M_Personalization_Page_Title_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách sản phẩm.
        /// </summary>
        public static string M_Product_Panel_Title {
            get {
                return ResourceManager.GetString("M_Product_Panel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string M_Product_Table_Col_Category {
            get {
                return ResourceManager.GetString("M_Product_Table_Col_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã.
        /// </summary>
        public static string M_Product_Table_Col_Code {
            get {
                return ResourceManager.GetString("M_Product_Table_Col_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        public static string M_Product_Table_Col_Name {
            get {
                return ResourceManager.GetString("M_Product_Table_Col_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán lẻ (NET).
        /// </summary>
        public static string M_Product_Table_Col_NET_Price {
            get {
                return ResourceManager.GetString("M_Product_Table_Col_NET_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán buôn (NET).
        /// </summary>
        public static string M_Product_Table_Col_NET_Price_NPP {
            get {
                return ResourceManager.GetString("M_Product_Table_Col_NET_Price_NPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán lẻ (VAT).
        /// </summary>
        public static string M_Product_Table_Col_VAT_Price {
            get {
                return ResourceManager.GetString("M_Product_Table_Col_VAT_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán buôn (VAT).
        /// </summary>
        public static string M_Product_Table_Col_VAT_Price_NPP {
            get {
                return ResourceManager.GetString("M_Product_Table_Col_VAT_Price_NPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị hệ thống.
        /// </summary>
        public static string M_System_Page_Title {
            get {
                return ResourceManager.GetString("M_System_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền nhóm, thành viên, chức năng, chuyên mục, bài viết và quảng cáo.
        /// </summary>
        public static string M_System_Page_Title_Desc {
            get {
                return ResourceManager.GetString("M_System_Page_Title_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách thành viên.
        /// </summary>
        public static string M_User_Panel_Title {
            get {
                return ResourceManager.GetString("M_User_Panel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư điện tử.
        /// </summary>
        public static string M_User_Table_Col_Email {
            get {
                return ResourceManager.GetString("M_User_Table_Col_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đầy đủ.
        /// </summary>
        public static string M_User_Table_Col_FullName {
            get {
                return ResourceManager.GetString("M_User_Table_Col_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string M_User_Table_Col_Mobile {
            get {
                return ResourceManager.GetString("M_User_Table_Col_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string M_User_Table_Col_Status {
            get {
                return ResourceManager.GetString("M_User_Table_Col_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string M_User_Table_Col_Username {
            get {
                return ResourceManager.GetString("M_User_Table_Col_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh.
        /// </summary>
        public static string Menu_System_Adv {
            get {
                return ResourceManager.GetString("Menu_System_Adv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết.
        /// </summary>
        public static string Menu_System_Article {
            get {
                return ResourceManager.GetString("Menu_System_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string Menu_System_Category1 {
            get {
                return ResourceManager.GetString("Menu_System_Category1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục.
        /// </summary>
        public static string Menu_System_Category2 {
            get {
                return ResourceManager.GetString("Menu_System_Category2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu.
        /// </summary>
        public static string Menu_System_Data {
            get {
                return ResourceManager.GetString("Menu_System_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers.
        /// </summary>
        public static string Menu_System_Developers {
            get {
                return ResourceManager.GetString("Menu_System_Developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo lỗi.
        /// </summary>
        public static string Menu_System_Error {
            get {
                return ResourceManager.GetString("Menu_System_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm.
        /// </summary>
        public static string Menu_System_Group {
            get {
                return ResourceManager.GetString("Menu_System_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng.
        /// </summary>
        public static string Menu_System_Menu {
            get {
                return ResourceManager.GetString("Menu_System_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết lập.
        /// </summary>
        public static string Menu_System_Setting {
            get {
                return ResourceManager.GetString("Menu_System_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành viên.
        /// </summary>
        public static string Menu_System_User {
            get {
                return ResourceManager.GetString("Menu_System_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to javascript:system.adv.list({0});.
        /// </summary>
        public static string Pager_Adv {
            get {
                return ResourceManager.GetString("Pager_Adv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to javascript:system.article.list({0});.
        /// </summary>
        public static string Pager_Article {
            get {
                return ResourceManager.GetString("Pager_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to javascript:system.article.articleInMenu({0});.
        /// </summary>
        public static string Pager_ArticleInMenu {
            get {
                return ResourceManager.GetString("Pager_ArticleInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to javascript:system.error.list({0});.
        /// </summary>
        public static string Pager_Errors {
            get {
                return ResourceManager.GetString("Pager_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to javascript:system.group.list({0});.
        /// </summary>
        public static string Pager_Group {
            get {
                return ResourceManager.GetString("Pager_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ảnh.
        /// </summary>
        public static string Pager_Info_Adv {
            get {
                return ResourceManager.GetString("Pager_Info_Adv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chuyên mục.
        /// </summary>
        public static string Pager_Info_Category {
            get {
                return ResourceManager.GetString("Pager_Info_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lỗi.
        /// </summary>
        public static string Pager_Info_Error {
            get {
                return ResourceManager.GetString("Pager_Info_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} nhóm.
        /// </summary>
        public static string Pager_Info_Group {
            get {
                return ResourceManager.GetString("Pager_Info_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chức năng.
        /// </summary>
        public static string Pager_Info_Menu {
            get {
                return ResourceManager.GetString("Pager_Info_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sản phẩm.
        /// </summary>
        public static string Pager_Info_SKU {
            get {
                return ResourceManager.GetString("Pager_Info_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} thành viên.
        /// </summary>
        public static string Pager_Info_User {
            get {
                return ResourceManager.GetString("Pager_Info_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to javascript:system.product.list({0});.
        /// </summary>
        public static string Pager_SKU {
            get {
                return ResourceManager.GetString("Pager_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to javascript:system.user.list({0});.
        /// </summary>
        public static string Pager_User {
            get {
                return ResourceManager.GetString("Pager_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo Thực chạy theo Hợp Đồng.
        /// </summary>
        public static string R_T_Contract {
            get {
                return ResourceManager.GetString("R_T_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo Thực chạy theo Phòng Ban.
        /// </summary>
        public static string R_T_Departments {
            get {
                return ResourceManager.GetString("R_T_Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo Thực chạy theo Nhóm Làm Việc.
        /// </summary>
        public static string R_T_Group {
            get {
                return ResourceManager.GetString("R_T_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo Thực chạy theo Bộ Phận.
        /// </summary>
        public static string R_T_Parts {
            get {
                return ResourceManager.GetString("R_T_Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo Thực chạy theo Sản phẩm.
        /// </summary>
        public static string R_T_Product {
            get {
                return ResourceManager.GetString("R_T_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo Thực chạy theo Nhân Viên.
        /// </summary>
        public static string R_T_Staff {
            get {
                return ResourceManager.GetString("R_T_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo Thực chạy theo Website.
        /// </summary>
        public static string R_T_Website {
            get {
                return ResourceManager.GetString("R_T_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adpage.
        /// </summary>
        public static string S_H_C_P_W_Adpage {
            get {
                return ResourceManager.GetString("S_H_C_P_W_Adpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balloon Ads.
        /// </summary>
        public static string S_H_C_P_W_Balloon_Ads {
            get {
                return ResourceManager.GetString("S_H_C_P_W_Balloon_Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner CPD.
        /// </summary>
        public static string S_H_C_P_W_Banner_CPD_1 {
            get {
                return ResourceManager.GetString("S_H_C_P_W_Banner_CPD_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner CPD chuyên trang.
        /// </summary>
        public static string S_H_C_P_W_Banner_CPD_2 {
            get {
                return ResourceManager.GetString("S_H_C_P_W_Banner_CPD_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxapp CPD.
        /// </summary>
        public static string S_H_C_P_W_Boxapp_CPD {
            get {
                return ResourceManager.GetString("S_H_C_P_W_Boxapp_CPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxapp CPM.
        /// </summary>
        public static string S_H_C_P_W_Boxapp_CPM {
            get {
                return ResourceManager.GetString("S_H_C_P_W_Boxapp_CPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxapp MultiBrand.
        /// </summary>
        public static string S_H_C_P_W_Boxapp_MultiBrand {
            get {
                return ResourceManager.GetString("S_H_C_P_W_Boxapp_MultiBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxapp SelfServing.
        /// </summary>
        public static string S_H_C_P_W_Boxapp_SelfServing {
            get {
                return ResourceManager.GetString("S_H_C_P_W_Boxapp_SelfServing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPA.
        /// </summary>
        public static string S_H_C_P_W_CPA {
            get {
                return ResourceManager.GetString("S_H_C_P_W_CPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPC Admarket.
        /// </summary>
        public static string S_H_C_P_W_CPC_Admarket {
            get {
                return ResourceManager.GetString("S_H_C_P_W_CPC_Admarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPC Plus.
        /// </summary>
        public static string S_H_C_P_W_CPC_Plus {
            get {
                return ResourceManager.GetString("S_H_C_P_W_CPC_Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPM Admarket.
        /// </summary>
        public static string S_H_C_P_W_CPM_Admarket {
            get {
                return ResourceManager.GetString("S_H_C_P_W_CPM_Admarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPM Mass.
        /// </summary>
        public static string S_H_C_P_W_CPM_Mass {
            get {
                return ResourceManager.GetString("S_H_C_P_W_CPM_Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng tin.
        /// </summary>
        public static string S_H_C_P_W_DT {
            get {
                return ResourceManager.GetString("S_H_C_P_W_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Ads.
        /// </summary>
        public static string S_H_C_P_W_GoogleAds {
            get {
                return ResourceManager.GetString("S_H_C_P_W_GoogleAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string S_H_C_P_W_Mobile {
            get {
                return ResourceManager.GetString("S_H_C_P_W_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm khác.
        /// </summary>
        public static string S_H_C_P_W_Other {
            get {
                return ResourceManager.GetString("S_H_C_P_W_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsored Post.
        /// </summary>
        public static string S_H_C_P_W_Sponsored_Post {
            get {
                return ResourceManager.GetString("S_H_C_P_W_Sponsored_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVC Online.
        /// </summary>
        public static string S_H_C_P_W_TVC_Online {
            get {
                return ResourceManager.GetString("S_H_C_P_W_TVC_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện tất cả các cột.
        /// </summary>
        public static string S_H_C_Show_All {
            get {
                return ResourceManager.GetString("S_H_C_Show_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng Khuyến mại.
        /// </summary>
        public static string S_H_C_SLKM {
            get {
                return ResourceManager.GetString("S_H_C_SLKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng Nội bộ.
        /// </summary>
        public static string S_H_C_SLNB {
            get {
                return ResourceManager.GetString("S_H_C_SLNB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng Thực chạy.
        /// </summary>
        public static string S_H_C_SLTC {
            get {
                return ResourceManager.GetString("S_H_C_SLTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ẩn hiện cột.
        /// </summary>
        public static string S_H_C_Title {
            get {
                return ResourceManager.GetString("S_H_C_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền Khuyến mại.
        /// </summary>
        public static string S_H_C_TTKM {
            get {
                return ResourceManager.GetString("S_H_C_TTKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền Nội bộ.
        /// </summary>
        public static string S_H_C_TTNB {
            get {
                return ResourceManager.GetString("S_H_C_TTNB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền Thực chạy.
        /// </summary>
        public static string S_H_C_TTTC {
            get {
                return ResourceManager.GetString("S_H_C_TTTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin của bạn đã được gửi đi. Chúng tôi sẽ liên lạc lại với bạn trong thời gian sớm nhất!.
        /// </summary>
        public static string Send_Message_Complete {
            get {
                return ResourceManager.GetString("Send_Message_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng có lỗi xảy ra. Vui lòng quay lại sau..
        /// </summary>
        public static string Send_Message_Error {
            get {
                return ResourceManager.GetString("Send_Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần điền các thông tin trước khi gửi..
        /// </summary>
        public static string Send_Message_Warning {
            get {
                return ResourceManager.GetString("Send_Message_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác.
        /// </summary>
        public static string Table_Col_Action {
            get {
                return ResourceManager.GetString("Table_Col_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string Table_Col_RowNumber {
            get {
                return ResourceManager.GetString("Table_Col_RowNumber", resourceCulture);
            }
        }
    }
}
